org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# Minecraft / mappings
minecraft_version=26.2
loader_version=0.19.3

# Mod info
mod_id=skilltree
mod_name=Passive Skill Tree
mod_version=0.7.6+c
mod_group_id=daripher.skilltree
mod_authors=Daripher
mod_description=Adds passive skill tree with player class system

# Version de la Fabric API officielle pour 26.2
fabric_api_version= 0.157.0+26.2
mod_menu_version=20.0.1

# --- DÉPENDANCES MODRINTH CRYPTÉES 26.2 ---
# Cardinal Components API
cardinal_components_id=K01OU20C
cardinal_components_version=d78LiKJ8

# Trinkets Updated
trinkets_id=XaT8sLP6
trinkets_version=to3SIE4i

# AttributeFix
attributefix_id=lOOpEntO
attributefix_version=DwUCU2Y7
